#spring:
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: future
#      username: future
#      password: future
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#      max-active: 10

server:
  context-path: /future
  port: 80

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 5000
      idle-timeout: 30000
  jms:
    pub-sub-domain: true
  redis:
      host: 192.168.1.17
      port: 6379
      password: future
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2
        # 连接池中的最小空闲连接
        min-idle: 2
      # 0 用于数据存储 1 用于分布式session
      database: 1



