#spring:
#  data:
#    mongodb:
#      database: future
#      host: 192.168.1.17
#      port: 27017
#      username: future
#      password: future
#      authentication-database: future
#      repositories:
#          enabled: true


